common: avb_tsn: Remove inclusion of clock_config.h
To avoid such compile error:

	harpoon-apps/common/libs/avb_tsn/stats_task.c:9:10: fatal error: clock_config.h: No such file or directory
	    9 | #include "clock_config.h"
	      |          ^~~~~~~~~~~~~~~~
	compilation terminated.

None of the functions defined in this header file are used in this
source file.

Signed-off-by: Stephane Viau <stephane.viau@nxp.com>