common: libs: import gen_sw_mbox library
Import gen_sw_mbox library to fix build issues faced when building on
MCUX SDK NG v25.06.00, due to conflicting headers, like follows:

"""
/path/to/gen_avb_sdk/common/net.h:35:9: error: implicit declaration of
function 'os_memcpy'; did you mean 'memcpy'?
[-Werror=implicit-function-declaration]
   35 |         os_memcpy(eth->dst, mac_dst, 6);
      |         ^~~~~~~~~
      |         memcpy
"""
As the header 'os/string.h' is defined in 'gen_avb_sdk/os/string.h',
'heterogeneous-multicore/include/os/string.h' and
'harpoon-apps/comon/os/string.h'.
And various other headers:
- os/assert.h
- common/list.h
- os/stdlib.h

Importing this library would allow to reduce these dependencies and to
align with other harpoon-apps libraries by using the
rtos-abstraction-layer.

repository: https://github.com/nxp-real-time-edge-sw/heterogeneous-multicore.git
commit: 1c985e1b3bb46d9b5c76dae8c7c2c44b9f3e689d ("Apply Real-time Edge
v2.9 release)
path: libs/gen_sw_mbox

Signed-off-by: Aziz Sellami <aziz.sellami@nxp.com>