industrial: remove useless pointer check
The check is useless and causing compilation issue on gcc 12.2:

harpoon-apps/industrial/avb_tsn/tsn_app/tsn_task.c: In function 'tsn_task_unregister':
harpoon-apps/industrial/avb_tsn/tsn_app/tsn_task.c:784:9: error: the comparison will always
evaluate as 'true' for the address of 'thread' will never be NULL [-Werror=address]
  784 |     if (&(*task)->thread)
      |         ^
In file included from harpoon-apps/industrial/avb_tsn/tsn_app/tsn_task.c:7:
harpoon-apps/industrial/avb_tsn/tsn_app/tsn_task.h:94:19: note: 'thread' declared here
   94 |     rtos_thread_t thread;
      |                   ^~~~~~

Signed-off-by: Marouen Ghodhbane <marouen.ghodhbane@nxp.com>