industrial: freertos: disable array-bounds error
Fix following compile issue:
"""
In function 'ENET_SetTsISRHandler',
    inlined from 'ENET_Ptp1588ConfigureHandler' at
/home/nxf95737/Projects/HRPN/main-ng/workspace/mcuxsdk/mcuxsdk/drivers/enet/fsl_enet.c:2890:5:
/home/nxf95737/Projects/HRPN/main-ng/workspace/mcuxsdk/mcuxsdk/drivers/enet/fsl_enet.c:458:16:
error: array subscript 2 is above array bounds of 'void (*[2])(ENET_Type
*, enet_handle_t *)' {aka 'void (*[2])(ENET_Type *, struct _enet_handle
*)'} [-Werror=array-bounds=]
  458 |     s_enetTsIsr[instance] = ISRHandler;
      |     ~~~~~~~~~~~^~~~~~~~~~
"""
Due to assert in mcuxsdk-core/drivers/enet/fsl_enet.c#194 (in
ENET_GetInstance) being skipped by enabling '-DNDEBUG'.
Disabling this warning allows compilation.

Signed-off-by: Aziz Sellami <aziz.sellami@nxp.com>